### ISSUE TITLE
Fix all F score issues in Code Climate

### ISSUE THREAD

**Issue by alchemyst** [alchemyst/Skogestad-Python#216]
We aim for high-quality readable code. We don't want Fs in Code Climate. Click [here](https://codeclimate.com/github/alchemyst/Skogestad-Python/code?q=rating%3AF) and keep fixing things until there's nothing in that list.

**Comment by DrakennekarD** [comment]
@alchemyst 
utils.py and utilsplot.py had F scores and have improved to a score of D. The checksums of the various commits to complete this issue are as follows (newest to oldest):

8c85634f4a636741916d9ef67daeb5f13697d1fb 6bb9454a3b1b747319703fb5868339eb02c7468e
472d9240828cde4666b2965e8df02ca42ab10d01 04c0d7b51b1c099505a4da703c7d2e9e9040ae15
6638d527557f346784704a735d44120b031458f2 30c7176224778cba0047e2eb56ab726432c441b2
bf063ab166049013c778bb4b6a0ed84f13343f0a ccda9ab8a4e3c819fc79bdd19646a671e4074a7b

Additionally, other code ratings have also been improved:

![image](https://cloud.githubusercontent.com/assets/25669383/25146804/8e617f2c-2475-11e7-9375-5df65766d911.png)
