### ISSUE TITLE
Add internal delay capability to models

### ISSUE THREAD

**Issue by alchemyst** [alchemyst/Skogestad-Python#262]
At the moment our `tf` object can only handle rational functions with the option one time delay. This causes an issue when calculating transfer functions like `1 + G` if `G` contains a time delay. This issue is for allowing some kind of resolution for this so that we can calculate closed loop transfer functions for systems with delays.

**Comment by GregLaycock** [comment]
Dibs

**Comment by darren-roos** [comment]
I do not mind trying to get this started. My plan would be to implement something similar to that of what matlab does. See https://www.mathworks.com/help/control/examples/specifying-time-delays.html#d120e709 for more details.

My first step will be to get this working for SISO systems.

Having looked at the current siso TF code, the potential problems I foresee are: 

- calculating the inverse in cases where it is not physically realizable
- the need to write an ODE solver that handles time delay for step responses
- handling of pole and zero calculations (my current idea is to have to alternate calculations: one that uses a root finding algorithm which would be unstable, and one that uses a zero order pade like matlab: https://www.mathworks.com/help/control/ref/pole.html#d120e101850 Note: a higher order pade could likely also be used with little increased difficulty)

**Comment by ilayn** [comment]
If you keep the delay information out of the rational parts you can do operations a bit more conveniently. For SISO models output delays and input delays are the same hence might be a good place the start.
