### ISSUE TITLE
Re-write polygcd and polylcm

### ISSUE THREAD

**Issue by NicVDMey** [alchemyst/Skogestad-Python#275]
The polygcd and polylcm methods currently rely on the Euclidean algorithm, however this only works for numbers that can be represented exactly in binary, so most float values will cause the algorithm to break. Forcing the coefficient of the polynomials to integers won't work, because any rounding will also cause the Euclidean algorithm to break. polygcd is used to get the zeros of mimotf objects and polylcm is used in tf2ss, so both of these methods will probably have issues if using floating point coefficients. A new approach for the gcd and lcm that doesn't rely on the Euclidean algorithm is needed.

**Comment by ilayn** [comment]
For LCM, I'm using a similar result to Karcanias, Mitrouli, "System theoretic based characterisation and computation of the least common multiple of a set of polynomials", Lin Alg App, 381, 2004. The results is acceptable but never stress tested it to the extremes. 

For GCD, Sylvester-matrix based methods are sufficiently good for medium difficulty/size problems.
