### ISSUE TITLE
Implement tf2ss for multivariable systems

### ISSUE THREAD

**Issue by alchemyst** [alchemyst/Skogestad-Python#64]
There is a procedure highlighted in [this paper](http://seit.unsw.adfa.edu.au/staff/sites/hrp/papers/pota96a-j.pdf)

**Comment by ilayn** [comment]
Hi Carl, 

Apologies for jumping in right away. I actually started to implement many of these MIMO algorithms as a full-fledged and quite possibly over-ambitious [harold project here](https://github.com/ilayn/harold) . I have most of the object creation and lti properties parts working but I don't have any documentation or demo yet. 

However I can test state <--> transfer conversions and they are pretty stable if compared to matlab results. You can have a look at it (search for `transfertostate` function). And if you like it, I might be able to convert it to the `python-control` syntax.

I actually want to use this great project of yours as a guinea pig such that the requirements of this project can be my deliverables list, can you please let me know if it sounds interesting to you too?

**Comment by alchemyst** [comment]
I am very interested! I'm starting to think that there is enough momentum behind control in Python now that it would make sense to try to pull together a couple of the groups working in this field. Your project looks really nice, and I must admit that the fact that much of the code in this project is student-created places a certain cap on the quality achievable. I have invested heavily in automating testing and code quality checking in this project to keep the cruft to a minimum, but most of the contributors are novice programmers and it shows. I'd love to get rid of the slicot dependency since my students are mostly unable to get it going on their (windows) machines. I am also keen to migrate to Python 3, so your project is already a step in the right direction.

Perhaps we can take this conversation off-list and discuss how we can optimally work together? My contact details are on my [university webpage](www.up.ac.za/chemeng/csandrock)

**Comment by ilayn** [comment]
Definitely. You can also use the gitter chat room link given in the readme of `harold`. I'll drop you an email soon. 

But the reason I wrote here was seriously about the tf2ss issue ;) I think I can cook up a function for your syntax too if needed. I only need to strip off a `num`,`den` the rest can be carried over word by word.

**Comment by MrMikeWolf** [comment]
Carl the site in the first comment called "this paper" does not open as it needs a username and password

**Comment by ilayn** [comment]
Its DOI is [10.1109/13.485241](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=485241) . Let me know if you need it. But notice that it can be numerically problematic especially with almost cancellations. A better one is the classical Section 4.4 of W.A. Wolowich, Linear Multivariable Systems (1974).
